<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-S4S1GDB" failures="1" tests="3" name="Test" time="101.209" errors="0" timestamp="2023-04-28T16:29:32 IST">
  <testcase classname="test.Sign_up_test" name="Sign_up_first" time="19.988"/>
  <testcase classname="test.Sign_up_test" name="sign_up_second_page" time="7.298"/>
  <testcase classname="test.Sign_up_test" name="third_page_sign_up" time="65.688">
    <failure type="java.lang.AssertionError" message="expected [Account Application
Sucessfully Submitted!] but found [Account Application
Sucessfully Submitted!]">
      <![CDATA[java.lang.AssertionError: expected [Account Application
Sucessfully Submitted!] but found [Account Application
Sucessfully Submitted!]
at test.Sign_up_test.third_page_sign_up(Sign_up_test.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- third_page_sign_up -->
</testsuite> <!-- Test -->
